name: Build

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20.18.1
  ELECTRON_VERSION: 32.2.7

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install dependencies
        run: npm install

      - name: run build script for windows
        if: startsWith(matrix.os,'windows')
        shell: powershell
        run: |
          build-windows.ps1

      - name: run build script for ubuntu
        if: startsWith(matrix.os,'ubuntu')
        shell: bash
        run: |
          chmod +x build-linux.sh
          ./build-linux.sh

      - name: run build script for macOS
        if: startsWith(matrix.os,'macOS')
        shell: bash
        run: |
          chmod +x build-macos.sh
          ./build-macos.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: prebuilds/*
